### ISSUE TITLE
Maybe you don't need to assign the value to the variable twice

### ISSUE THREAD

**Issue by YejuJ** [COMP2522/project-yumo-john-lucas-viet#73] opened 2023-03-27 23:31 UTC
https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/4a5d15650abe6b9a041e7d6d9de6e29e26de6810/src/main/java/org/myProject/obj/PlaneObj.java#L262

https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/4a5d15650abe6b9a041e7d6d9de6e29e26de6810/src/main/java/org/myProject/obj/PlaneObj.java#L267

**Comment by John2T** [comment] 2023-03-28 01:52
This issue is a duplicate of a previous issue and has been fixed

**Closed by John2T** 2023-03-28 01:52 UTC
