### ISSUE TITLE
Missing implementationof DB class

### ISSUE THREAD

**Issue by NicRodri** [COMP2522/project-yumo-john-lucas-viet#46] opened 2023-03-27 21:56 UTC
https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/77ac8aebb3f7c459ff871b9bf1c56cbe2c52007f/src/main/java/org/myProject/DB.java#L3

this is an empty class

**Comment by John2T** [comment] 2023-03-28 02:57
Duplicate of #25

**Closed by John2T** 2023-03-28 02:57 UTC
